openapi: 3.0.1
info:
  title: HotelPackage
  description: API Definition of HotelPackage
  version: 1.0.0
servers:
- url: http://localhost:8290/HotelPackage
paths:
  /:
    get:
      responses:
        default:
          description: Default response
