openapi: 3.0.1
info:
  title: mainurl
  description: API Definition of mainurl
  version: 1.0.0
servers:
- url: http://localhost:8290/mainurl
paths:
  /:
    get:
      responses:
        default:
          description: Default response
