openapi: 3.0.1
info:
  title: traveler
  description: API Definition of traveler
  version: 1.0.0
servers:
- url: http://localhost:8290/traveler
paths:
  /:
    get:
      responses:
        default:
          description: Default response
