openapi: 3.0.1
info:
  title: user
  description: API Definition of user
  version: 1.0.0
servers:
- url: http://localhost:8290/user
paths:
  /:
    get:
      responses:
        default:
          description: Default response
